### DISCUSSION TITLE
增加 Primitive 特性

### DISCUSSION THREAD

**Discussion by cloudwu** [ejoy/ant#169] [Ideas]
今天我增加了一个预制几何体的特性，取代之前在 ant.entity|entity 中的 api 。见 https://github.com/ejoy/ant/pull/166

之前的
```lua
world:create_entity {
	policy = {
		"ant.render|simplerender",
	},
	data = {
		scene 		= {
			s = {250, 1, 250},
		},
		material 	= "/pkg/ant.resources/materials/mesh_shadow.material",
		visible     = true,
		mesh_result        = ientity.plane_mesh(),
	}
}
```
就可以写成

```lua
world:create_entity {
	policy = {
		"ant.render|render",
	},
	data = {
		scene 		= {
			s = {250, 1, 250},
		},
		material 	= "/pkg/ant.resources/materials/mesh_shadow.material",
		visible     = true,
		mesh        = "plane.primitive",
	}
}
```

这里的 mesh 之前是填写 vfs 路径。目前 .primitive 后缀被扩展为调用一段代码生成 mesh 。可以传参数，参数编码在字符串中。比如箭头可以写成 ""arrow(0.3).primitive" 。

我希望未来支持更多的几何体，比如立方体、球、等等。有没有人愿意做这个事情？可以直接提 pr 。

**Comment by constly** [comment]
过两天放假我来尝试加下~

**Reply by cloudwu** [reply]
球面网格建议用 Icosphere ，即用 20 面体逼近。算法参考：

* https://danielsieger.com/blog/2021/03/27/generating-spheres.html
* https://blog.codingnow.com/2021/10/cube_sphere.html

生成函数应提供一个参数即大致的总三角形数，再由总面数换算成 Icosphere  算法参数（这样的接口参数方便换成其它生成算法）。

如果是圆柱体，也使用总三角形数做参数，换算成底面的圆的分段数。

**Reply by cloudwu** [reply]
分支已合并，可以直接对 master 提 pr 。

**Reply by constly** [reply]
以前我还想过戴森球那个球形地图是怎么做的，这次正好借这个机会尝试一翻~

**Reply by cloudwu** [reply]
戴森球用的 uvsphere ，这会导致赤道到两级不均匀。我认为，如果是逻辑上给球面规划网格，像戴森球那样摆机器铺传送带的话，用 cube sphere 最好（我记得无人深空就是这么干的）。戴森球我玩的时候真的是逼死强迫症。

但这里是为了让球面的三角形更均匀，所以建议用 icosphere 。

**Comment by constly** [comment]
这个 "arrow(0.3).primitive" 怎么使用呢，我这样使用：
```lua
world:create_entity {
	policy = {
		"ant.render|render",
	},
	data = {
		scene 		= {
			s = {1, 1, 1},	-- 缩放
			t = {0, 1, 0},	-- 位置
		},
		material 	= "/pkg/ant.resources/materials/mesh_shadow.material",
		visible     = true,
		mesh        = "arrow(0.3).primitive",
	}
}
```
会报错:
```lua
[2024-06-07 12:38:53.49][ERROR]( ant.window|window ) Layout: a_texcoord0, is not declared or not equal to varyings defined
stack traceback:
        ( service:6 )
        G:/ant/ant/pkg/ant.render/render_system/render_system.lua:199: in upvalue 'check_varyings'
        G:/ant/ant/pkg/ant.render/render_system/render_system.lua:216: in local 'f'
        G:/ant/ant/pkg/ant.world/main.lua:476: in field '_pipeline_entity_init'
        G:/ant/ant/pkg/ant.world/main.lua:61: in method '_flush_entity_queue'
        G:/ant/ant/pkg/ant.world/entity_system.lua:63: in local 'func'
        G:/ant/ant/pkg/ant.world/main.lua:379: in upvalue 'update_func'
        G:/ant/ant/pkg/ant.world/main.lua:404: in field '_pipeline_update'
        G:/ant/ant/pkg/ant.world/main.lua:588: in method 'pipeline_update'
        G:/ant/ant/pkg/ant.window/service/window.lua:76: in upvalue 'f'
```

**Reply by cloudwu** [reply]
arrow 只支持颜色，不能绑贴图。这里还需要统一一下。我只是随手翻译了原来 ant.entity 的代码。

https://github.com/ejoy/ant/blob/master/test/features/pkg/ant.test.features/test/shadow_test.lua#L122

**Comment by constly** [comment]
我目前还在尝试绘制cube，有一些基础问题想请教下：  

1. 在使用"plane.primitive"时，如何在material中指定其贴图，以及如何在运行时修改贴图呢

2. 在绘制cube时，如果cube也要支持贴图，我能用“Triangle Strip”方式绘制吗（由于我还没搞明白怎么设置贴图，所以无法测试）。但如果用Strip方式，我发现必须得在material中指定 PT: TRISTRIP ，这可能与其他primitive的材质参数不一样，用Triangle List的方式应该更通用一些。总之我现在不太清楚应该用Triangle List，还是用Triangle Strip来绘制cube。这两种方式的区别在于我传的[ibdata](https://github.com/constly/ant_demo/blob/92f72a2edbc0fa93ede1d83a6eab381ee86b5fc8/startup/games/demo/demo/core/core_11.lua#L148)不一样，Strip方式传的数据要少一些。

**Reply by cloudwu** [reply]
指定贴图的问题：

首先需要定义一个有贴图的材质，我暂时没在引擎 ant.resources下找到合适的已经定义好的材质适合 primitive 用。试了 text_plane.material 和 texquad.material 都画不出来，这个需要 @junjie020 确认一下为啥？接下来是不是应该在 ant.resources 下增加一个专门绘制 primitive 的材质比较好？

所以，我稍微改了一下 mesh_shadow.material 这个文件，增加了贴图属性 `s_basecolor`：
```
fx:
  shader_type: PBR
  setting:
    lighting: on
    cast_shadow: off
    receive_shadow: on
  varyings:
    a_position: vec3
    a_normal: vec3
    a_texcoord0: vec2
    v_texcoord0: vec2
    v_posWS: "vec3 TEXCOORD1"
    v_normal: "vec3 TEXCOORD2"
properties:
  s_basecolor:
    stage: 0
    texture: /pkg/ant.resources/textures/black.texture  # 默认贴图
  u_pbr_factor: {0.2, 0.8, 0, 1}  #metallic, roughness, alpha_cutoff, occlusion strength
  u_emissive_factor: {0, 0, 0, 0}
  u_basecolor_factor: {0.8, 0.8, 0.8, 1.0}
state:
  ALPHA_REF: 0
  CULL: CCW
  DEPTH_TEST: GREATER
  MSAA: true
  WRITE_MASK: RGBAZ
```
然后就可以这样用了：
```lua
world:create_entity {
	policy = {
		"ant.render|render",
	},
	data = {
		scene 	= { s = {10, 1, 10}  },
		material 	= "/asset/plane.material",   -- 上面这个材质
		visible     = true,
		mesh        = "plane.primitive",
		on_ready = function (e)
			-- 更换默认贴图
			local tex = assetmgr.resource "/pkg/ant.resources/textures/color_text.texture"
			imaterial.set_property(e, "s_basecolor", tex.id)
		end,
	},
}
```

我觉得 primitive 应该使用 Triangle List ，因为像 cube 这样的六面体，六个面可能不应该共用顶点。因为不同面虽然空间上共用了顶点，但这些顶点在不同面上的法向量是不同的 。cube 的数据可以参考 bgfx 的例子：https://github.com/bkaradzic/bgfx/blob/master/examples/21-deferred/deferred.cpp#L91-L117
